export enum ACTION_TYPES {
	FETCH_DATA = 'APP/FETCH_DATA',
	REQUEST_DATA = 'APP/REQUEST_DATA',
	SHOW_LOADER = 'APP/SHOW_LOADER',
	HIDE_LOADER = 'APP/HIDE_LOADER',
}

export enum INNER_CONTENT_TYPES {
	REBUILD_DESIGN = 'APP/REBUILD_DESIGN',
	SHOW_BUTTON_LOADER = 'APP/BUTTON_LOADER',
	NOTIFICATION = 'APP/NOTIFICATION',
	ADD_PAGINATED_ITEMS = 'APP/ADD_PAGINATED_ITEMS'
}